#!/usr/bin/fish

# Get configured 
set USER_DIR (arduino-cli config dump | yq r - 'directories.user')

# Pull WifiManger Source
gh repo clone tzapu/WiFiManager
cd WiFiManager

# Only the development branch supports ESP32
git checkout development
cd ..

# Copy into arduino-cli library folder
sudo cp -r WiFiManager/ $USER_DIR/libraries/WiFiManager32/

# Clean up
sudo rm -r WiFiManager 

